services: 

  mysql:
    image: mysql:8.0
    container_name: mysql_prueba
    ports:
      - "3308:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "prueba"
  mi_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3500:80"

    